apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodered.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nodered.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nodered.service.type }}
  ports:
    - name: nodered
      port: {{ .Values.nodered.service.ports.nodered.port }}
      targetPort: {{ .Values.nodered.service.ports.nodered.targetPort }}
      protocol: {{ .Values.nodered.service.ports.nodered.protocol }}
      {{- if and (or (eq .Values.nodered.service.type "NodePort") (eq .Values.nodered.service.type "LoadBalancer")) (not (empty .Values.nodered.service.ports.nodered.nodePort)) }}
      nodePort: {{ .Values.nodered.service.ports.nodered.nodePort }}
      {{- end }}
  selector:
    {{- include "nodered.selectorLabels" . | nindent 4 }}
