apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
spec:
  {{- if not .Values.core.autoscaling.enabled }}
  replicas: {{ .Values.core.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "core.labels" . | nindent 8 }}
    spec:
      {{- with .Values.core.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.core.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.core.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.core.podSecurityContext | nindent 8 }}
      containers:
        - name: core
          securityContext:
            {{- toYaml .Values.core.securityContext | nindent 12 }}
          image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.core.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.core.service.ports.api.containerPort }}
              protocol: {{ .Values.core.service.ports.api.protocol }}
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
          env:
            - name: API_PORT
              value: {{ .Values.core.service.ports.api.containerPort | quote }}
            - name: NODERED_URL
              value: {{ include "nodered.noderedUrl" . | quote }}
          {{- with .Values.core.envVars }}
            - name: SMART_ORCHESTRATOR_URL
              value: {{ .smartOrchestratorUrl | quote }}
            - name: VALID_NODES
              value: {{ .validNodes | quote }}
            - name: HELM_CHART_REPOSITORY
              value: {{ .helmChartRepository | quote }}
            - name: LTSE_URL
              value: {{ .ltseUrl | quote }}
            - name: LTSE_INDEX
              value: {{ .ltseIndex | quote }}
          {{- end }}
